# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM golang:alpine AS builder

WORKDIR /app

# Cache Go modules
COPY go.mod go.sum ./

RUN go mod download

# Copy the source code
COPY . .

# Build the MCP server binary
RUN go build -o mcp-filesystem-server main.go

FROM alpine:latest
WORKDIR /app

# Copy the built binary from the builder stage
COPY --from=builder /app/mcp-filesystem-server ./

# Create a directory that will be used as allowed directory
RUN mkdir -p /app

ENTRYPOINT ["./mcp-filesystem-server"]
CMD ["/app"]
